language: java
dist: trusty
jdk: oraclejdk8
script: mvn package
deploy:
  provider: releases
  api_key: "$GITHUB_AUTH_TOKEN"
  file: "target/Spellbound-$TRAVIS_TAG.jar"
  prerelease: true
  skip_cleanup: true
  on:
    tags: true